export const UPDATE_REAL_TIME_PRICING = 'UPDATE_REAL_TIME_PRICING';

export const UPDATE_BATCH_DATA = 'UPDATE_BATCH_DATA';

export const SAGA_START_SYNC_REAL_TIME_PRICING =
  'SAGA_START_SYNC_REAL_TIME_PRICING';

export const SAGA_STOP_SYNC_REAL_TIME_PRICING =
  'SAGA_STOP_SYNC_REAL_TIME_PRICING';

export const SAGA_START_SYNC_BATCH_DAYLY_DATA = 'SAGA_START_SYNC_BATCH_DATA';

export const SAGA_STOP_SYNC_BATCH_DAYLY_DATA = 'SAGA_STOP_SYNC_BATCH_DATA';

export const SAGA_START_SYNC_BATCH_INTRADAY_DATA =
  'SAGA_START_SYNC_BATCH_INTRADAY_DATA';

export const SAGA_STOP_SYNC_BATCH_INTRADAY_DATA =
  'SAGA_STOP_SYNC_BATCH_INTRADAY_DATA';
