export const UPDATE_REAL_TIME_PRICING = 'UPDATE_REAL_TIME_PRICING';

export const UPDATE_BATCH_DATA = 'UPDATE_BATCH_DATA';

export const SAGA_START_SYNC_REAL_TIME_PRICING = 'SAGA_START_SYNC_REAL_TIME_PRICING';

export const SAGA_STOP_SYNC_REAL_TIME_PRICING = 'SAGA_STOP_SYNC_REAL_TIME_PRICING';

export const SAGA_START_SYNC_BATCH_DAYLY_DATA = 'SAGA_START_SYNC_BATCH_DATA';

export const SAGA_STOP_SYNC_BATCH_DAYLY_DATA = 'SAGA_STOP_SYNC_BATCH_DATA';
// export const SAGA_FETCH_BATCH_DATA = 'SAGA_FETCH_BATCH_DATA';
